extends:
  - "react-app"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
  - "prettier/react"
parser: "@typescript-eslint/parser"
rules:
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars":
    - "error"
    - 
      vars: "all"
      args: "after-used"
      ignoreRestSiblings: false
      varsIgnorePattern: "^_"
