extends:
  - "react-app"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
  - "prettier/react"
parser: "@typescript-eslint/parser"
